### ISSUE TITLE
[OP ZW] = CMP_BRK?

### ISSUE THREAD

**Issue by devjiangzhou** [adah1972/libunibreak#26]
In the pair table
[OP ZW] = CMP_BRK
[OP CM] = PRH_BRK
Does not match https://www.unicode.org/reports/tr14/tr14-38.html#CombiningMarks, why is this?

**Comment by adah1972** [comment]
Since Revision 38 took out Table 2 and crossed out the Combining Marks section, the table content was copied from Revision 37, as noted in the code — ‘This is a direct mapping of Table 2 of Unicode Standard Annex 14, Revision 37, except for ZWJ (manually adjusted after special processing as per LB8a of Revision 41) and CB (manually added as per LB20).’

**Comment by devjiangzhou** [comment]
thanks
